language: python

python:
    - 3.6
    - 3.5
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

install:
    - 'pip install pipenv'
    - 'pipenv sync --dev'

script:
    - coverage run --source=atomium -m unittest discover tests

after_success:
  - coveralls
